### ISSUE TITLE
Support new Icons

### ISSUE THREAD

**Issue by MrDrache333** [kevneuftrois/iOS14icons#1]
I like your icons a lot, thanks 🙏
If you have the time to add some more, i would like you to add the following 😄:
- DS Video
- DS Audio
- DS Get
- DS Finder
- DS File
- Moments
- MyJDownloader2
- OpenVPN
- PiHole
- AdGuard

**Comment by kevneuftrois** [comment]
Thank you for your request! I will add the requested icons tomorrow before evening 😃

**Comment by kevneuftrois** [comment]
Unfortunately I'll have to wait till sunday since my surface doesn't work as good as my pc does. I'll be back home on sunday and i'll immediately upload your requested files. Sorry for the circumstances. 😅

**Comment by kevneuftrois** [comment]
Hello, your requested icons were uploaded. Some might still get some smaller changes but for now they're online 😃
